version: "3"
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER} 
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
